#!/usr/bin/env bash
# Configures the web server
# Also adds a custom header
sudo apt update -y
sudo apt install nginx -y
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo bash -c 'cat <<EOF> /etc/nginx/sites-enabled/default
	server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	add_header X-Served-By \$hostname;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}

}
EOF'
sudo service nginx restart
