#!/usr/bin/env bash
# Say "Best School" by default
# Say "bad luck" the 4th time
# Say "good luck" the 8th time
# On a loop 10 times

i=1
while [ $i -le 10 ]
do 
    if [ $i -eq 4 ]
    then
        echo "bad luck";
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School";         
    fi

    (("i++"));
done
