#!/usr/bin/env bash
# Loop 20 times
# say "bad luck from China" on 4th loop
# say "bad luck from Japan" on 9th loop
# say "bad luck from Italy" on 17th loop

i=1
while [ $i -le 20 ]
do 
    echo $i; 
    case $i in
    4)
        echo "bad luck from China"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    esac
    (("i++"));
done
